#!/bin/bash

echo "my name is Mrs Ujunwa Ozouli, married to Engr Ikechukwu Ozouli"
echo "i am 29years old and i am new to software Engineering"
echo "i live at no 3 Oxford street GRA Enugu"
echo "i am currently working on my project"
  
#ask a question on who is reading this 
echo 'who is this?"
echo "$name"
echo "welcome $name"
echo "todays date is $date"
echo "this computer has this memory storage"
memory= free -h
echo "$memory"
 
